version: '3.7'
services:

    ping:
        build: ping

    calc:
        build: calc

    soma:
        build: soma

    sub:
        build: sub
    
    mult1:
        build: ./mult
        container_name: mult1
        environment:
        - CONTAINER_NAME=mult1

    mult2:
        build: ./mult
        container_name: mult2
        environment:
        - CONTAINER_NAME=mult2

    mult3:
        build: ./mult
        container_name: mult3
        environment:
        - CONTAINER_NAME=mult3

    nginx:
        container_name: nginx
        build: nginx
        ports:
            - 80:80
        depends_on:
           - ping
           - calc
           - soma
           - sub
           - mult1
           - mult2
           - mult3
